### PR TITLE
Submission modal

### PR DESCRIPTION
**Pull request by carletex**
- Moves the submission form to a modal.
- View it on Github / Submit buttons at the beginning and end of the challenge. 
- Skeleton until the markdown loads.
- Disabled button + tooltip for Non-registered users.

### CODE REVIEW

**Comment by carletex** [comment]
Some screenshots:

image
Untitled
image

**Comment by dgrcode** [comment]
There's something broken with the submit button. I can't submit with any hardhat account.

**Comment by carletex** [comment]
@dgrcode You mean the "submit challenge" (in the challenge page) or the "submit" button (in the modal)?

I've just fixed one thing so admins can also submit challenges. Other than that, it works for me.

What error are you getting?

**Comment by dgrcode** [comment]
I meant on the challenge page, but it's fixed now. I was probably using admin accounts only to test 😂

**Pull request merged**
