### PR TITLE
Markdown for challenges description

### PR DESCRIPTION
**Pull request by carletex**
- [x] Install react markdown
- [x] Load the markdown dynamically for each challenge (created the `simple-nft-example.md`)
- [x] Create the remaining MD files from github challanges (remove the telegram / buidlguidl stuff -  take simple-nft-example.md as example)
- [x] Style the markdown. Two options
  1. [Chakra default styles 
  2. `<ReactMarkdown className="markdown">` and create custom styles for markdown > (p, blockquotes, pre, code, etc).

### CODE REVIEW

**Comment by carletex** [comment]
@dgrcode you can take it from here IYW. If not, I'll continue with it later today.

**Comment by dgrcode** [comment]
I'm on it. Made some updates related to stylings. I need to fix an issue with inline code and haven't made a commit yet. Will push once I fix it this afternoon.

**Comment by dgrcode** [comment]
@carletex check the styles. I've used the ReactMarkdown approach with a utility package to combine it with ChakraUI. I'll add the rest of the MD documents tomorrow morning.

**Comment by carletex** [comment]
Looks greats! And love the approach. Pushed a commit: 

- Reduce the container size
- Fix a useEffect deps.

For some reason it doesn't pick up the `<h1>` styles you defined in `chakraMarkdownTheme.jsx`. It using size 5xl instead of 2xl.

image

> I'll add the rest of the MD documents tomorrow morning.

Check this first #91. It seems the new repo it not updated yet, but I those challenges are the one we are using now.

**Comment by dgrcode** [comment]
Yep, there's something weird with the font sizes. I just saw this in the docs:

> If you use the size prop, the font size of the heading will automatically decrease in size for smaller screens

So it looks like using `size` is more flexible, but it doesn't match the fontSize prop 1:1. I think we want to use `size`, but maybe make them smaller.

I just tested a smaller size and it looks good. Will commit.

**Comment by dgrcode** [comment]
Some things that we should probably let Austin know:
 - Challenges missing: 3, 4, 6, 7
 - Challenge 5 is named challenge 3 throughout the readme. I didn't update it because it's also in links, so probably someone should look at what needs to be updated.

Also, some nice-to-have that we're missing:
 - Syntax highlighting. [This](minimum-viable-exchange) could be a starting point
 - Copy button on code blocks. Should be simple.
 - check lists are shown as `[ ]` in the resulting web. We can do some fancy transformation on the list items.

**Comment by dgrcode** [comment]
I also made a rebase, that's why it's force pushed 😬

**Pull request merged**
