### PR TITLE
[WIP] Builder role

### PR DESCRIPTION
**Pull request by carletex**
- [x] Add builder role
- [x] Registered role for new users
- [x] Give the builder role to registered users when an admin accepts a new challenge
- [x] Tweak setUserRole front-end logic
- [x] Show builder badge
- [x] Create firabase migration 
  - [x] isAdmin: true => role: "admin".
  - [x] role: "registered" if NOT ACCEPTED Challenges
  - [x] role: "builder" if user has ACCEPTED challenges
- [ ] **Enhance:** util, something like: isRegistered, hasBuilderPermission, hasAdminPermission
- [ ] **Enhance:** user / role context.

### CODE REVIEW

**Review by dgrcode — APPROVED** [review]
Things work as expected and code looks good. Some things I've seen that we might to enhance in the future:
 1. When a user becomes a builder (after a challenge submitted has been approved), they don't get any feedback that they became a builder. We might want to show them a banner or something when their role changed. Maybe the bell we had before for notifications could be useful here.
 2. So far we're allowing ppl to submit any challenge without taking into account the order.
 3. The address flashes the modal to register before the user is fully loaded. We might want to show a spinner while we get the user and their role.

I'll open issues for the 2 and 3. What do you think about 1?

**Comment by carletex** [comment]
@dgrcode 

> What do you think about 1?

They don't get a notification but they get a "bulider" badge next to their address: 
builder

**Comment by dgrcode** [comment]
Yes, I noticed the badge, but I'm not sure everybody would notice. And I also doubt they know what that means, like having access to the builder list, build list, and being able to submit new builds.

**Comment by carletex** [comment]
When they get the builder role, they also start seeing the "builders" and "builds" links on the navbar, which I think it makes it more obvious.

**Pull request merged**
