### PR TITLE
[WIP] Dark mode

### PR DESCRIPTION
**Pull request by carletex**
- [x] Chakra color mode set up (I think the initial color mode is not working)
- [x] Create a position fixed Switcher.
- [x] Add an sun / moon icon next to the switcher
- [x] Dark mode Styles for the whole app (including markdown). We can use the moonshot collective colors. https://moonshotcollective.space/

### CODE REVIEW

**Comment by carletex** [comment]
@dgrcode wanna take it from here?

**Comment by dgrcode** [comment]
yep, I'll take it.

**Comment by dgrcode** [comment]
Before merging I'd like to:
 - [ ] Put all the hooks used in https://github.com/moonshotcollective/scaffold-directory/pull/94/commits/9bfa4c679868d02c39042597a7e0034894e1d6f2 into a custom hook that exports the colors for different types of texts, backgrounds, borders, etc, to avoid having declarations all over the place. That way we can just update the custom hook and get all colors updated at once.
 - [ ] Use the hook `useColorModeValue` whenever I'm defining the boolean `isLightMode`. I didn't realise it could be used for components (like the moon/sun icons)

**Comment by dgrcode** [comment]
@carletex ready for testing. I haven't implemented moonshot collective colors, but this adds an initial iteration on dark mode that we can personalise further in another issue. Or, if this is a priority I can continue with this tomorrow morning and do it as part of this issue to avoid creating new ones.

**Comment by carletex** [comment]
Rebased, fixed conflicts and fixed the ToDo on the active style for the /portfolio route.

**Pull request merged**
