### PR TITLE
Prettier changes before #18

### PR DESCRIPTION
**Pull request by dgrcode**
This is another dummy PR just to prettify some code and have a clean diff once I open a PR for #18. There shouldn't be behaviour changes, just prettier.

### CODE REVIEW

**Comment by carletex** [comment]
Could you upload a `.eslintrc.js` and/or `.prettierrc` for this on the backend folder? That's actually this issue #7 

I'm guessing you are applying your IDE defaults, but my IDE needs those files (on parent folders), so right now I'm not getting any linting help inside the `backend` folder. Not sure if we just want to copy the ones on `react-app`

**Review by sogasg — APPROVED** [review]
Did this at the exact same time as @carletex comment above.

**Comment by sogasg** [comment]
> Could you upload a `.eslintrc.js` and/or `.prettierrc` for this on the backend folder? That's actually issue #7
> 
> I'm guessing you are applying your IDE defaults, but my IDE needs those files (on parent folders), so right now I'm not getting any linting help inside the `backend` folder. Not sure if we just want to copy the ones on `react-app`

I think it's good if we use the same format for the backend and the `react-app`.

**Comment by dgrcode** [comment]
yep, I'll add those files and actually close 7 with this PR. Will do that shortly, currently working on #18 🧑‍🏭

**Comment by dgrcode** [comment]
Fix #7

**Pull request merged**
